spring.application.name=api-gateway

# Render dynamic port
server.port=${PORT:8080}

# ---- EUREKA ----
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=true

# ---- SERVICE DISCOVERY ----
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ---- JWT ----
jwt.secret=${JWT_SECRET}

# ---- LOGGING ----
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.cloud.loadbalancer=INFO

# ---- ACTUATOR ----
management.endpoints.web.exposure.include=gateway,health,info

# ---- CORS (Frontend Production + Local) ----
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173,https://zixo.vercel.app
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true